spring.application.name=api
# 1. H2 Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:h2:mem:memorydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 2. Arka planda çalışan SQL'leri konsolda görmek için
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Yazdığımız Entity sınıflarına bakarak tabloları OTOMATİK oluştur!
spring.jpa.hibernate.ddl-auto=update

# 4. H2'nin arayüzüne tarayıcıdan erişebilmek için
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
